// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class BulletBase;	// External class reference
	class B_9x21_Ball;	// External class reference
	
	class rhs_ammo_9x17 : B_9x21_Ball {
		audibleFire = 100;
	};
	
	class rhs_ammo_792x57_Ball : BulletBase {
		audibleFire = 100;
		dangerRadiusHit = 5;
		suppressionRadiusBulletClose = 6;
		suppressionRadiusHit = 8;
	};
};
