// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class SoldierGB;	// External class reference
	
	class rhsgref_cdf_ngd_base : SoldierGB {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsgref_cdf_ngd_rifleman;	// External class reference
	
	class rhsgref_cdf_ngd_officer : rhsgref_cdf_ngd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_ngd_grenadier : rhsgref_cdf_ngd_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhsgref_cdf_ngd_machinegunner : rhsgref_cdf_ngd_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhsgref_cdf_ngd_squadleader : rhsgref_cdf_ngd_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_ngd_grenadier_rpg : rhsgref_cdf_ngd_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_cdf_ngd_engineer : rhsgref_cdf_ngd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_ngd_crew : rhsgref_cdf_ngd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_reg_base : SoldierGB {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsgref_cdf_reg_rifleman;	// External class reference
	
	class rhsgref_cdf_reg_general : rhsgref_cdf_reg_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_reg_officer : rhsgref_cdf_reg_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_reg_grenadier : rhsgref_cdf_reg_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhsgref_cdf_reg_machinegunner : rhsgref_cdf_reg_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhsgref_cdf_reg_marksman : rhsgref_cdf_reg_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsgref_cdf_reg_squadleader : rhsgref_cdf_reg_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_reg_grenadier_rpg : rhsgref_cdf_reg_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_cdf_reg_specialist_aa : rhsgref_cdf_reg_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_cdf_reg_engineer : rhsgref_cdf_reg_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_reg_crew : rhsgref_cdf_reg_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_air_pilot : rhsgref_cdf_reg_crew {
		asr_ai_level = 8;
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_para_base : rhsgref_cdf_reg_base {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsgref_cdf_para_rifleman;	// External class reference
	
	class rhsgref_cdf_para_officer : rhsgref_cdf_para_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_para_machinegunner : rhsgref_cdf_para_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhsgref_cdf_para_marksman : rhsgref_cdf_para_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsgref_cdf_para_squadleader : rhsgref_cdf_para_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_para_grenadier_rpg : rhsgref_cdf_para_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_cdf_para_specialist_aa : rhsgref_cdf_para_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_cdf_para_engineer : rhsgref_cdf_para_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_cdf_para_crew : rhsgref_cdf_para_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_nat_base : SoldierGB {
		asr_ai_level = 6;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsgref_nat_rifleman;	// External class reference
	
	class rhsgref_nat_grenadier_rpg : rhsgref_nat_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_nat_specialist_aa : rhsgref_nat_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_nat_scout : rhsgref_nat_base {
		asr_ai_level = 5;
	};
	
	class rhsgref_nat_saboteur : rhsgref_nat_base {
		asr_ai_level = 5;
		camouflage = 2.0;
	};
	
	class rhsgref_nat_crew : rhsgref_nat_base {
		camouflage = 2.0;
	};
	class rhsgref_nat_pmil_rifleman;	// External class reference
	
	class rhsgref_nat_pmil_grenadier_rpg : rhsgref_nat_pmil_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_nat_pmil_specialist_aa : rhsgref_nat_pmil_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_nat_pmil_scout : rhsgref_nat_pmil_rifleman {
		asr_ai_level = 5;
	};
	
	class rhsgref_nat_pmil_saboteur : rhsgref_nat_pmil_rifleman {
		asr_ai_level = 5;
		camouflage = 2.0;
	};
	
	class rhsgref_nat_pmil_crew : rhsgref_nat_pmil_rifleman {
		camouflage = 2.0;
	};
	
	class rhsgref_ins_base : SoldierGB {
		asr_ai_level = 6;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsgref_ins_reed;	// External class reference
	class rhsgref_ins_uniform_izlom;	// External class reference
	class rhsgref_ins_uniform_specter;	// External class reference
	class rhsgref_ins_uniform_gorka_y;	// External class reference
	
	class rhsgref_ins_squadleader : rhsgref_ins_uniform_specter {
		asr_ai_level = 5;
	};
	
	class rhsgref_ins_grenadier_rpg : rhsgref_ins_uniform_izlom {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsgref_ins_specialist_aa : rhsgref_ins_reed {
		secondaryAmmoCoef = 0.5;
	};
	class rhsgref_ins_uniform_gorka_g;	// External class reference
	
	class rhsgref_ins_engineer : rhsgref_ins_uniform_gorka_g {
		camouflage = 2.0;
	};
	
	class rhsgref_ins_saboteur : rhsgref_ins_uniform_specter {
		asr_ai_level = 5;
		camouflage = 2.0;
	};
	
	class rhsgref_ins_sniper : rhsgref_ins_uniform_izlom {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsgref_ins_spotter : rhsgref_ins_uniform_gorka_y {
		asr_ai_level = 2;
	};
	
	class rhsgref_ins_crew : rhsgref_ins_uniform_specter {
		camouflage = 2.0;
	};
	
	class rhsgref_ins_pilot : rhsgref_ins_uniform_specter {
		asr_ai_level = 9;
		camouflage = 2.0;
	};
};
