// Generated by unRap v1.06 by Kegetys

class CfgWeapons {
	class ItemCore;	// External class reference
	class InventoryOpticsItem_Base_F;	// External class reference
	
	class rhs_acc_scope_base : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 1;
		};
	};
	
	class rhsgref_acc_oko21 : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 0;
		};
	};
	class InventoryMuzzleItem_Base_F;	// External class reference
	class muzzle_snds_H;	// External class reference
	
	class rhsgref_silencer_base : muzzle_snds_H {
		class ItemInfo : InventoryMuzzleItem_Base_F {
			class AmmoCoef;	// External class reference
		};
	};
	
	class rhsgref_savz61_suppressor : rhsgref_silencer_base {
		class ItemInfo : ItemInfo {
			class AmmoCoef : AmmoCoef {
				visibleFire = 0.2;
				audibleFire = 0.2;
			};
		};
	};
	class Uniform_Base;	// External class reference
	
	class rhsgref_uniform_ttsko_forest : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_ttsko_mountain : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_ttsko_urban : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_vsr : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_para_ttsko_oxblood : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_para_ttsko_mountain : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_para_ttsko_urban : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_specter : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_reed : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_alpenflage : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_flecktarn : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class rhsgref_uniform_flecktarn_full : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_tigerstripe : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_woodland : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_uniform_woodland_olive : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class rhsgref_uniform_ERDL : Uniform_Base {
		asr_camouflage = 0.3;
	};
	class rhs_6b23;	// External class reference
	
	class rhsgref_6b23_khaki : rhs_6b23 {
		asr_camouflage = 0.4;
	};
	class rhsgref_6b23_khaki_rifleman;	// External class reference
	class rhsgref_6b23_khaki_sniper;	// External class reference
	class rhsgref_6b23_khaki_officer;	// External class reference
	class rhsgref_6b23_khaki_nco;	// External class reference
	class rhsgref_6b23_khaki_medic;	// External class reference
	
	class rhsgref_6b23_ttsko_forest : rhsgref_6b23_khaki {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_forest_rifleman : rhsgref_6b23_khaki_rifleman {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain : rhsgref_6b23_khaki {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain_rifleman : rhsgref_6b23_khaki_rifleman {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain_sniper : rhsgref_6b23_khaki_sniper {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain_officer : rhsgref_6b23_khaki_officer {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain_nco : rhsgref_6b23_khaki_nco {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_mountain_medic : rhsgref_6b23_khaki_medic {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi : rhsgref_6b23_khaki {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi_rifleman : rhsgref_6b23_khaki_rifleman {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi_sniper : rhsgref_6b23_khaki_sniper {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi_officer : rhsgref_6b23_khaki_officer {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi_nco : rhsgref_6b23_khaki_nco {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_6b23_ttsko_digi_medic : rhsgref_6b23_khaki_medic {
		asr_camouflage = 0.3;
	};
	class rhsgref_otv_khaki;	// External class reference
	
	class rhsgref_otv_digi : rhsgref_otv_khaki {
		asr_camouflage = 0.3;
	};
	
	class rhsgref_TacVest_ERDL : rhsgref_6b23_khaki_rifleman {
		asr_camouflage = 0.3;
	};
	
	class rhs_6b5 : rhs_6b23 {
		asr_camouflage = 0.4;
	};
	class Rifle_Base_F;	// External class reference
	
	class Rifle_Short_Base_F : Rifle_Base_F {};
	
	class rhs_weap_kar98k_Base_F : Rifle_Base_F {
		modes[] = {"SemiAuto", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_m38_Base_F : Rifle_Base_F {
		modes[] = {"SemiAuto", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_m70_base : Rifle_Base_F {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Burst_far", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 100;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 7;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 50;
			midRangeProbab = 0.7;
			maxRange = 100;
			maxRangeProbab = 0.2;
		};
		
		class AI_Burst_far : AI_Burst_close {
			burst = 4;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 5;
			minRange = 400;
			minRangeProbab = 0.05;
			midRange = 500;
			midRangeProbab = 0.3;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 300;
			minRangeProbab = 0.8;
			midRange = 400;
			midRangeProbab = 0.5;
			maxRange = 600;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 300;
			minRangeProbab = 0.8;
			midRange = 400;
			midRangeProbab = 0.5;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
			showToPlayer = 1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_m92 : rhs_weap_m70_base {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 30;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 15;
			midRangeProbab = 0.7;
			maxRange = 30;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 120;
			minRangeProbab = 0.8;
			midRange = 200;
			midRangeProbab = 0.6;
			maxRange = 600;
			maxRangeProbab = 0.01;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 250;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 30;
			midRangeProbab = 0.8;
			maxRange = 60;
			maxRangeProbab = 0.1;
			showToPlayer = 1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
		};
	};
	
	class rhs_weap_m76 : rhs_weap_m70_base {
		modes[] = {"SemiAuto", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
	};
	
	class rhs_weap_m21_base : rhs_weap_m70_base {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2", "AI_far"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 20;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 700;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 900;
			maxRangeProbab = 0.1;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		
		class AI_far : Single {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 5;
			reloadtime = 0.2;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 4;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 600;
			midRangeProbab = 0.05;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
	};
	
	class rhs_weap_m21s : rhs_weap_m21_base {
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 20;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 700;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 900;
			maxRangeProbab = 0.1;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		
		class AI_far : Single {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 5;
			reloadtime = 0.2;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 4;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 600;
			midRangeProbab = 0.05;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
	};
	
	class rhs_weap_m21a_pr : rhs_weap_m21_base {};
	
	class rhs_weap_m21s_pr : rhs_weap_m21a_pr {
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 20;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 700;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 900;
			maxRangeProbab = 0.1;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		
		class AI_far : Single {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 5;
			reloadtime = 0.2;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 4;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 600;
			midRangeProbab = 0.05;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
	};
	
	class SMG_01_Base : Rifle_Short_Base_F {
		class Single;	// External class reference
		class FullAuto;	// External class reference
	};
	
	class SMG_01_F : SMG_01_Base {};
	
	class rhs_weap_savz61 : SMG_01_F {
		modes[] = {"Single", "FullAuto", "AI_Burst_close"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.9;
			midRange = 80;
			midRangeProbab = 0.5;
			maxRange = 300;
			maxRangeProbab = 0.01;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.8;
			maxRange = 20;
			maxRangeProbab = 0.4;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 20;
			minRangeProbab = 0.8;
			midRange = 30;
			midRangeProbab = 0.5;
			maxRange = 60;
			maxRangeProbab = 0.4;
		};
	};
};
