// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class BulletBase;	// External class reference
	class B_556x45_Ball;	// External class reference
	
	class rhssaf_ammo_556x45_EPR : B_556x45_Ball {
		audibleFire = 100;
	};
	
	class rhssaf_ammo_556x45_SOST : B_556x45_Ball {
		audibleFire = 100;
	};
	
	class rhssaf_ammo_556x45_SPR : B_556x45_Ball {
		audibleFire = 100;
	};
	
	class rhs_ammo_792x57_Ball : BulletBase {
		audibleFire = 100;
		dangerRadiusBulletClose = 100;
		dangerRadiusHit = 5;
		suppressionRadiusBulletClose = 6;
		suppressionRadiusHit = 8;
	};
};
