// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_rhs_saf_c {
		addonRootClass = "rhssaf_c_weapons";
		units[] = {};
		weapons[] = {};
		ammo[] = {"rhssaf_ammo_556x45_EPR", "rhssaf_ammo_556x45_SOST", "rhssaf_ammo_556x45_SPR", "rhs_ammo_792x57_Ball"};
		requiredVersion = 1.7;
		requiredAddons[] = {"asr_ai3_main", "A3_Characters_F", "A3_Weapons_F", "rhssaf_c_troops", "rhssaf_c_weapons"};
		version = 1.1.0.98;
		author = "Robalo";
	};
};
