// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class rhssaf_Kitbag_base;	// External class reference
	
	class rhssaf_kitbag_md2camo : rhssaf_Kitbag_base {
		asr_camouflage = 0.9;
	};
	
	class rhssaf_kitbag_digital : rhssaf_Kitbag_base {
		asr_camouflage = 0.9;
	};
	
	class rhssaf_kitbag_smb : rhssaf_Kitbag_base {
		asr_camouflage = 1.0;
	};
	class SoldierGB;	// External class reference
	
	class rhssaf_soldier_base : SoldierGB {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhssaf_soldier_army_digital_base;	// External class reference
	class rhssaf_army_m10_digital_rifleman_m21;	// External class reference
	
	class rhssaf_army_m10_digital_rifleman_ammo : rhssaf_army_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_asst_mgun : rhssaf_army_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_sq_lead : rhssaf_soldier_army_digital_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_sniper_m76 : rhssaf_soldier_army_digital_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhssaf_army_m10_digital_spotter : rhssaf_army_m10_digital_rifleman_m21 {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_rifleman_at : rhssaf_soldier_army_digital_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhssaf_army_m10_digital_asst_spec_at : rhssaf_army_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_asst_spec_aa : rhssaf_army_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_medic : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_repair : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_exp : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_engineer : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_crew : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_crew_armored : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_crew_armored_nco : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_digital_officer : rhssaf_soldier_army_digital_base {
		camouflage = 2.0;
	};
	class rhssaf_soldier_army_oakleaf_summer_base;	// External class reference
	class rhssaf_army_m93_oakleaf_summer_rifleman_m21;	// External class reference
	
	class rhssaf_army_m93_oakleaf_summer_rifleman_ammo : rhssaf_army_m93_oakleaf_summer_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_asst_mgun : rhssaf_army_m93_oakleaf_summer_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_sq_lead : rhssaf_soldier_army_oakleaf_summer_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_sniper_m76 : rhssaf_soldier_army_oakleaf_summer_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhssaf_army_m93_oakleaf_summer_spotter : rhssaf_army_m93_oakleaf_summer_rifleman_m21 {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_rifleman_at : rhssaf_soldier_army_oakleaf_summer_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhssaf_army_m93_oakleaf_summer_asst_spec_at : rhssaf_army_m93_oakleaf_summer_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_asst_spec_aa : rhssaf_army_m93_oakleaf_summer_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_medic : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_repair : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_exp : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_engineer : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_crew : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m93_oakleaf_summer_officer : rhssaf_soldier_army_oakleaf_summer_base {
		camouflage = 2.0;
	};
	class rhssaf_army_m10_para_rifleman_m21;	// External class reference
	
	class rhssaf_army_m10_para_rifleman_ammo : rhssaf_army_m10_para_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_asst_mgun_m84 : rhssaf_army_m10_para_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_asst_mgun_minimi : rhssaf_army_m10_para_rifleman_m21 {
		camouflage = 2.0;
	};
	class rhssaf_soldier_army_para_digital_base;	// External class reference
	
	class rhssaf_army_m10_para_sq_lead : rhssaf_soldier_army_para_digital_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_sniper_m76 : rhssaf_soldier_army_para_digital_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhssaf_army_m10_para_sniper_m82a1 : rhssaf_army_m10_para_sniper_m76 {
		asr_ai_level = 10;
	};
	
	class rhssaf_army_m10_para_spotter : rhssaf_army_m10_para_rifleman_m21 {
		asr_ai_level = 2;
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_rifleman_at : rhssaf_soldier_army_para_digital_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhssaf_army_m10_para_asst_spec_at : rhssaf_army_m10_para_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_asst_spec_aa : rhssaf_army_m10_para_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_medic : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_repair : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_exp : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_engineer : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_crew : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_army_m10_para_officer : rhssaf_soldier_army_para_digital_base {
		camouflage = 2.0;
	};
	class rhssaf_un_m10_digital_desert_rifleman_m21;	// External class reference
	
	class rhssaf_un_m10_digital_desert_rifleman_ammo : rhssaf_un_m10_digital_desert_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_asst_mgun : rhssaf_un_m10_digital_desert_rifleman_m21 {
		camouflage = 2.0;
	};
	class rhssaf_soldier_un_desert_base;	// External class reference
	
	class rhssaf_un_m10_digital_desert_sq_lead : rhssaf_soldier_un_desert_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_sniper_m76 : rhssaf_soldier_un_desert_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhssaf_un_m10_digital_desert_spotter : rhssaf_un_m10_digital_desert_rifleman_m21 {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_rifleman_at : rhssaf_soldier_un_desert_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhssaf_un_m10_digital_desert_asst_spec_at : rhssaf_un_m10_digital_desert_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_asst_spec_aa : rhssaf_un_m10_digital_desert_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_medic : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_repair : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_exp : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_engineer : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_crew : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_desert_officer : rhssaf_soldier_un_desert_base {
		camouflage = 2.0;
	};
	class rhssaf_un_m10_digital_rifleman_m21;	// External class reference
	
	class rhssaf_un_m10_digital_rifleman_ammo : rhssaf_un_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_asst_mgun : rhssaf_un_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	class rhssaf_soldier_un_digital_base;	// External class reference
	
	class rhssaf_un_m10_digital_sq_lead : rhssaf_soldier_un_digital_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_sniper_m76 : rhssaf_soldier_un_digital_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhssaf_un_m10_digital_spotter : rhssaf_un_m10_digital_rifleman_m21 {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_rifleman_at : rhssaf_soldier_un_digital_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhssaf_un_m10_digital_asst_spec_at : rhssaf_un_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_asst_spec_aa : rhssaf_un_m10_digital_rifleman_m21 {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_medic : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_repair : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_exp : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_engineer : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_crew : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
	
	class rhssaf_un_m10_digital_officer : rhssaf_soldier_un_digital_base {
		camouflage = 2.0;
	};
};
