// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class Grenade;	// External class reference
	class B_556x45_Ball;	// External class reference
	class B_762x51_Ball;	// External class reference
	class B_9x21_Ball;	// External class reference
	class R_PG32V_F;	// External class reference
	
	class rhs_ammo_3d17_shell : Grenade {
		aiAmmoUsageFlags = 4+ 8;
	};
	
	class rhs_B_545x39_Ball : B_556x45_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_545x39_7N6_Ball : rhs_B_545x39_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_545x39_7N10_Ball : rhs_B_545x39_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_545x39_7N22_Ball : rhs_B_545x39_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_545x39_7N24_Ball : rhs_B_545x39_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_545x39_7U1_Ball : rhs_B_545x39_Ball {
		audibleFire = 2;
		dangerRadiusBulletClose = 1;
		dangerRadiusHit = 5;
		suppressionRadiusBulletClose = 1;
	};
	
	class rhs_B_762x54_Ball : B_762x51_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_762x39_Ball : B_762x51_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_762x39_U_Ball : rhs_B_762x39_Ball {
		audibleFire = 2;
		dangerRadiusBulletClose = 1;
		dangerRadiusHit = 5;
		suppressionRadiusBulletClose = 1;
	};
	
	class rhs_B_9x39_SP5 : rhs_B_762x39_Ball {
		audibleFire = 2;
		dangerRadiusBulletClose = 1;
		dangerRadiusHit = 5;
		suppressionRadiusBulletClose = 1;
	};
	
	class rhs_rpg26_rocket : R_PG32V_F {
		audibleFire = 100;
		aiAmmoUsageFlags = 64+ 128+ 256+ 512;
	};
	
	class rhs_rpg7v2_pg7vl : rhs_rpg26_rocket {
		audibleFire = 100;
	};
	
	class rhs_rpg7v2_pg7vr : rhs_rpg7v2_pg7vl {
		aiAmmoUsageFlags = 128+ 512;
	};
	
	class rhs_rpg7v2_tbg7v : rhs_rpg7v2_pg7vl {
		aiAmmoUsageFlags = 64+ 128;
	};
	
	class rhs_rpg7v2_og7v : rhs_rpg7v2_pg7vl {
		aiAmmoUsageFlags = 64+ 256+ 128;
	};
	
	class rhs_B_9x19_7N21 : B_9x21_Ball {
		audibleFire = 100;
	};
	
	class rhs_B_9x18_57N181S : B_9x21_Ball {
		audibleFire = 100;
	};
};
