// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_rhs_ru_c {
		addonRootClass = "rhs_c_weapons";
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredVersion = 1.7;
		requiredAddons[] = {"asr_ai3_main", "A3_Characters_F", "A3_Weapons_F", "rhs_c_troops", "rhs_c_weapons", "rhs_cti_insurgents"};
		version = 1.1.1.99;
		author = "Robalo";
	};
	
	class asr_ai3_rhs_ru_camo_c {
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredVersion = 1.7;
		requiredAddons[] = {};
		author = "Robalo";
	};
};
