// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class B_AssaultPack_Base;	// External class reference
	
	class rhs_assault_umbts : B_AssaultPack_Base {
		asr_camouflage = 1.0;
	};
	
	class rhs_rpg : B_AssaultPack_Base {
		asr_camouflage = 1.0;
	};
	
	class rhs_sidor : B_AssaultPack_Base {
		asr_camouflage = 1.0;
	};
	
	class rhs_medic_bag : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	class SoldierGB;	// External class reference
	
	class rhs_infantry_msv_base : SoldierGB {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhs_msv_rifleman;	// External class reference
	
	class rhs_msv_machinegunner_assistant : rhs_msv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_msv_LAT : rhs_msv_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_msv_RShG2 : rhs_msv_LAT {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_msv_arifleman : rhs_msv_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_msv_grenadier_rpg : rhs_msv_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_msv_strelok_rpg_assist : rhs_msv_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_msv_marksman : rhs_msv_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_msv_efreitor : rhs_msv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_msv_sergeant : rhs_msv_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhs_msv_junior_sergeant : rhs_msv_sergeant {
		asr_ai_level = 4;
		camouflage = 2.0;
	};
	
	class rhs_msv_officer_armored : rhs_msv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_msv_at : rhs_msv_grenadier_rpg {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_msv_aa : rhs_msv_at {
		camouflage = 2.0;
	};
	
	class rhs_msv_engineer : rhs_msv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_msv_crew : rhs_msv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_msv_crew_commander : rhs_msv_crew {
		camouflage = 2.0;
	};
	
	class rhs_pilot_base : rhs_infantry_msv_base {
		asr_ai_level = 8;
		camouflage = 2.0;
	};
	class rhs_pilot_tan_base;	// External class reference
	
	class rhs_pilot_tan : rhs_pilot_tan_base {
		camouflage = 2.0;
	};
	class rhs_msv_emr_grenadier;	// External class reference
	
	class rhs_msv_emr_sergeant : rhs_msv_emr_grenadier {
		asr_ai_level = 3;
	};
	
	class rhs_msv_emr_junior_sergeant : rhs_msv_emr_sergeant {
		asr_ai_level = 4;
	};
	
	class rhs_msv_emr_efreitor : rhs_msv_emr_grenadier {
		camouflage = 2.0;
	};
	class rhs_mvd_izlom_rifleman;	// External class reference
	
	class rhs_mvd_izlom_rifleman_LAT : rhs_mvd_izlom_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_mvd_izlom_grenadier_rpg : rhs_mvd_izlom_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_mvd_izlom_arifleman : rhs_mvd_izlom_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_mvd_izlom_marksman : rhs_mvd_izlom_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_mvd_izlom_efreitor : rhs_mvd_izlom_rifleman_LAT {
		camouflage = 2.0;
	};
	
	class rhs_mvd_izlom_sergeant : rhs_mvd_izlom_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhs_infantry_vdv_base : rhs_infantry_msv_base {
		camouflage = 2.0;
	};
	class rhs_vdv_rifleman;	// External class reference
	
	class rhs_vdv_LAT : rhs_vdv_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_vdv_arifleman : rhs_vdv_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_vdv_marksman : rhs_vdv_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_vdv_machinegunner_assistant : rhs_vdv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_vdv_efreitor : rhs_vdv_LAT {
		camouflage = 2.0;
	};
	class rhs_vdv_rifleman_asval;	// External class reference
	
	class rhs_vdv_marksman_asval : rhs_vdv_rifleman_asval {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_vdv_sergeant : rhs_vdv_LAT {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhs_vdv_junior_sergeant : rhs_vdv_sergeant {
		asr_ai_level = 4;
		camouflage = 2.0;
	};
	
	class rhs_vdv_officer_armored : rhs_vdv_rifleman {
		camouflage = 2.0;
	};
	class rhs_vdv_grenadier;	// External class reference
	
	class rhs_vdv_grenadier_rpg : rhs_vdv_grenadier {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_vdv_at : rhs_vdv_grenadier_rpg {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_vdv_aa : rhs_vdv_at {
		camouflage = 2.0;
	};
	
	class rhs_vdv_strelok_rpg_assist : rhs_vdv_rifleman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_vdv_engineer : rhs_vdv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_vdv_crew : rhs_vdv_rifleman {
		camouflage = 2.0;
	};
	
	class rhs_vdv_crew_commander : rhs_vdv_crew {
		camouflage = 2.0;
	};
	
	class rhs_infantry_vdv_des_base : rhs_infantry_vdv_base {
		camouflage = 2.0;
	};
	
	class rhs_vdv_recon_rifleman : rhs_vdv_rifleman {
		asr_ai_level = 2;
		camouflage = 2.0;
	};
	
	class rhs_vdv_recon_marksman : rhs_vdv_recon_rifleman {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_vdv_recon_machinegunner_assistant : rhs_vdv_recon_rifleman {
		camouflage = 2.0;
	};
	class rhs_vdv_recon_rifleman_lat;	// External class reference
	
	class rhs_vdv_recon_efreitor : rhs_vdv_recon_rifleman_lat {
		camouflage = 2.0;
	};
	
	class rhs_vdv_recon_officer_armored : rhs_vdv_recon_rifleman {
		camouflage = 2.0;
	};
	class I_G_Soldier_F;	// External class reference
	
	class rhs_g_uniform1_base : SoldierGB {
		minFireTime = 10;
		camouflage = 2.0;
	};
	
	class rhs_ins_base : I_G_Soldier_F {
		asr_ai_level = 6;
		camouflage = 2.0;
	};
	
	class rhs_g_Soldier_AT_F : rhs_ins_base {
		secondaryAmmoCoef = 0.5;
	};
	class rhs_g_Soldier_GL_F;	// External class reference
	
	class rhs_g_Soldier_TL_F : rhs_g_Soldier_GL_F {
		asr_ai_level = 5;
	};
	
	class rhs_g_Soldier_M_F : rhs_ins_base {
		asr_ai_level = 5;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhs_g_Soldier_LAT_F : rhs_ins_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_g_Soldier_AAT_F : rhs_ins_base {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class rhs_g_Soldier_SL_F : rhs_ins_base {
		asr_ai_level = 5;
	};
	
	class rhs_g_Soldier_AA_F : rhs_ins_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhs_g_engineer_F : rhs_ins_base {
		camouflage = 2.0;
	};
	class rhs_rva_crew;	// External class reference
	
	class rhs_rva_crew_officer : rhs_rva_crew {
		camouflage = 2.0;
	};
};
