// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_incognito {
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredAddons[] = {CBA_MAIN, "asr_ai3_main"};
		requiredVersion = 1.7;
		author = "Rydygier";
	};
};
