// Generated by unRap v1.06 by Kegetys

class Extended_PostInit_EventHandlers {
	class asr_ai3_incognito {
		clientInit = "call compile preProcessFileLineNumbers '\x\asr_ai3\addons\incognito\XEH_postInitClient.sqf'";
	};
};
