// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_rhs_us_c {
		addonRootClass = "rhsusf_c_weapons";
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredVersion = 1.7;
		requiredAddons[] = {"asr_ai3_main", "A3_Characters_F", "A3_Weapons_F", "rhsusf_c_troops", "rhsusf_c_weapons"};
		version = 1.1.1.99;
		author = "Robalo";
	};
	
	class asr_ai3_rhs_us_camo_c {
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredVersion = 1.7;
		requiredAddons[] = {};
		author = "Robalo";
	};
};
