// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class B_AssaultPack_Base;	// External class reference
	class B_AssaultPack_rgr;	// External class reference
	
	class rhsusf_assault_eagleaiii_ucp : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	
	class rhsusf_assault_eagleaiii_coy : rhsusf_assault_eagleaiii_ucp {
		asr_camouflage = 1.0;
	};
	
	class rhsusf_falconii : B_AssaultPack_rgr {
		asr_camouflage = 0.9;
	};
	
	class rhsusf_falconii_mc : B_AssaultPack_rgr {
		asr_camouflage = 0.8;
	};
	class Weapon_Bag_Base;	// External class reference
	
	class RHS_M2_Gun_Bag : Weapon_Bag_Base {
		asr_camouflage = 1.2;
	};
	
	class RHS_M2_Tripod_Bag : Weapon_Bag_Base {
		asr_camouflage = 1.0;
	};
	class SoldierWB;	// External class reference
	
	class rhsusf_infantry_army_base : SoldierWB {
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsusf_army_ocp_rifleman;	// External class reference
	
	class rhsusf_army_ocp_riflemanl : rhsusf_army_ocp_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_autoriflemana : rhsusf_army_ocp_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_machinegunnera : rhsusf_army_ocp_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_officer : rhsusf_infantry_army_base {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_riflemanat : rhsusf_army_ocp_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsusf_army_ocp_marksman : rhsusf_infantry_army_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsusf_army_ocp_squadleader : rhsusf_infantry_army_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_teamleader : rhsusf_infantry_army_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_jfo : rhsusf_infantry_army_base {
		asr_ai_level = 3;
	};
	
	class rhsusf_army_ocp_javelin : rhsusf_army_ocp_riflemanat {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_javelin_assistant : rhsusf_army_ocp_riflemanat {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_aa : rhsusf_army_ocp_riflemanat {
		secondaryAmmoCoef = 0.5;
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_engineer : rhsusf_army_ocp_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_explosives : rhsusf_army_ocp_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_sniper : rhsusf_army_ocp_marksman {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
		asr_ai_level = 10;
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_crewman : rhsusf_infantry_army_base {
		camouflage = 2.0;
	};
	
	class rhsusf_army_ocp_helipilot : rhsusf_infantry_army_base {
		asr_ai_level = 8;
		camouflage = 2.0;
	};
	class rhsusf_infantry_usmc_base;	// External class reference
	class rhsusf_usmc_marpat_wd_rifleman;	// External class reference
	
	class rhsusf_usmc_marpat_wd_rifleman_light : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_autorifleman_m249_ass : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_machinegunner_ass : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_officer : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_riflemanat : rhsusf_usmc_marpat_wd_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsusf_usmc_marpat_wd_squadleader : rhsusf_usmc_marpat_wd_rifleman {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_teamleader : rhsusf_infantry_usmc_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_jfo : rhsusf_usmc_marpat_wd_rifleman {
		asr_ai_level = 3;
	};
	
	class rhsusf_usmc_marpat_wd_fso : rhsusf_usmc_marpat_wd_rifleman {
		asr_ai_level = 3;
	};
	
	class rhsusf_usmc_marpat_wd_smaw : rhsusf_usmc_marpat_wd_riflemanat {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_engineer : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_explosives : rhsusf_usmc_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_stinger : rhsusf_usmc_marpat_wd_smaw {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsusf_usmc_marpat_wd_marksman : rhsusf_usmc_marpat_wd_rifleman {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsusf_usmc_marpat_wd_spotter : rhsusf_usmc_marpat_wd_marksman {
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
		asr_ai_level = 2;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_sniper : rhsusf_usmc_marpat_wd_marksman {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
		asr_ai_level = 10;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_crewman : rhsusf_infantry_usmc_base {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_marpat_wd_helipilot : rhsusf_infantry_usmc_base {
		asr_ai_level = 8;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_lar_marpat_wd_rifleman : rhsusf_usmc_marpat_wd_rifleman {
		asr_ai_level = 3;
	};
	
	class rhsusf_usmc_lar_marpat_wd_rifleman_light : rhsusf_usmc_lar_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_lar_marpat_wd_riflemanat : rhsusf_usmc_lar_marpat_wd_rifleman {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsusf_usmc_lar_marpat_wd_autorifleman : rhsusf_infantry_usmc_base {
		asr_ai_level = 3;
	};
	
	class rhsusf_usmc_lar_marpat_wd_squadleader : rhsusf_usmc_lar_marpat_wd_rifleman {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_lar_marpat_wd_teamleader : rhsusf_infantry_usmc_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_lar_marpat_wd_marksman : rhsusf_usmc_lar_marpat_wd_rifleman {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsusf_usmc_lar_marpat_wd_crewman : rhsusf_infantry_usmc_base {
		asr_ai_level = 3;
		camouflage = 2.0;
	};
	
	class rhsusf_infantry_usmc_recon_base : rhsusf_infantry_usmc_base {
		asr_ai_level = 2;
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_recon_marpat_wd_rifleman_at : rhsusf_infantry_usmc_recon_base {
		secondaryAmmoCoef = 0.5;
	};
	
	class rhsusf_usmc_recon_marpat_wd_marksman : rhsusf_infantry_usmc_recon_base {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class rhsusf_usmc_recon_marpat_wd_officer : rhsusf_infantry_usmc_recon_base {
		camouflage = 2.0;
	};
	
	class rhsusf_usmc_recon_marpat_wd_teamleader : rhsusf_infantry_usmc_recon_base {
		camouflage = 2.0;
	};
	
	class rhsusf_socom_uniform_base : SoldierWB {
		minFireTime = 10;
	};
	class rhsusf_socom_mc_uniform;	// External class reference
	
	class rhsusf_infantry_socom_armysf_base : rhsusf_socom_mc_uniform {
		asr_ai_level = 1;
		minFireTime = 10;
		camouflage = 2.0;
	};
	class rhsusf_socom_g3_m81_uniform;	// External class reference
	
	class rhsusf_infantry_socom_marsoc_base : rhsusf_socom_g3_m81_uniform {
		asr_ai_level = 1;
		camouflage = 2.0;
	};
	class rhsusf_socom_marsoc_cso_cqb;	// External class reference
	
	class rhsusf_socom_marsoc_cso_light : rhsusf_socom_marsoc_cso_cqb {
		camouflage = 2.0;
	};
	
	class rhsusf_socom_marsoc_teamleader : rhsusf_infantry_socom_marsoc_base {
		camouflage = 2.0;
	};
	
	class rhsusf_socom_marsoc_elementleader : rhsusf_socom_marsoc_cso_cqb {
		camouflage = 2.0;
	};
	
	class rhsusf_socom_marsoc_cso_eod : rhsusf_infantry_socom_marsoc_base {
		camouflage = 2.0;
		canDeactivateMines = 1;
	};
	
	class rhsusf_socom_marsoc_cso_mechanic : rhsusf_infantry_socom_marsoc_base {
		camouflage = 2.0;
		engineer = 1;
	};
	
	class rhsusf_socom_marsoc_spotter : rhsusf_infantry_socom_marsoc_base {
		camouflage = 2.0;
	};
	
	class rhsusf_socom_marsoc_sniper : rhsusf_socom_marsoc_spotter {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
		asr_ai_level = 10;
		camouflage = 2.0;
	};
	
	class rhsusf_socom_marsoc_sniper_m107 : rhsusf_socom_marsoc_sniper {
		camouflage = 2.0;
	};
	class rhsusf_socom_swcc_crewman;	// External class reference
	
	class rhsusf_socom_swcc_officer : rhsusf_socom_swcc_crewman {
		camouflage = 2.0;
	};
	class rhsusf_usmc_marpat_wd_rifleman_m4;	// External class reference
	
	class rhsusf_airforce_jetpilot : rhsusf_usmc_marpat_wd_rifleman_m4 {
		asr_ai_level = 8;
	};
};
