// Generated by unRap v1.06 by Kegetys

class CfgWeapons {
	class ItemCore;	// External class reference
	class InventoryMuzzleItem_Base_F;	// External class reference
	class InventoryOpticsItem_Base_F;	// External class reference
	class muzzle_snds_H;	// External class reference
	
	class rhsusf_silencer_base : muzzle_snds_H {
		class ItemInfo : InventoryMuzzleItem_Base_F {
			class AmmoCoef;	// External class reference
		};
	};
	
	class rhsusf_acc_M2010S : rhsusf_silencer_base {
		class ItemInfo : ItemInfo {
			class AmmoCoef : AmmoCoef {
				visibleFire = 0.2;
				audibleFire = 0.2;
			};
		};
	};
	
	class rhsusf_acc_SR25S : rhsusf_silencer_base {
		class ItemInfo : ItemInfo {
			class AmmoCoef : AmmoCoef {
				visibleFire = 0.2;
				audibleFire = 0.2;
			};
		};
	};
	
	class rhsusf_acc_rotex5_grey : rhsusf_silencer_base {
		class ItemInfo : ItemInfo {
			class AmmoCoef : AmmoCoef {
				visibleFire = 0.2;
				audibleFire = 0.2;
			};
		};
	};
	
	class rhsusf_acc_nt4_black : rhsusf_silencer_base {
		class ItemInfo : ItemInfo {
			class AmmoCoef : AmmoCoef {
				visibleFire = 0.2;
				audibleFire = 0.2;
			};
		};
	};
	
	class rhsusf_acc_sniper_base : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 2;
		};
	};
	
	class rhsusf_acc_compm4 : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 0;
		};
	};
	
	class rhsusf_acc_ELCAN : rhsusf_acc_sniper_base {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 1;
		};
	};
	
	class rhsusf_acc_SpecterDR : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 1;
		};
	};
	
	class rhsusf_acc_ACOG : rhsusf_acc_sniper_base {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 1;
		};
	};
	
	class rhsusf_acc_ACOG_anpvs27 : rhsusf_acc_ACOG {
		class ItemInfo : ItemInfo {
			opticType = 1;
		};
	};
	
	class rhsusf_acc_LEUPOLDMK4_2 : rhsusf_acc_sniper_base {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 2;
		};
	};
	
	class rhsusf_acc_premier : rhsusf_acc_LEUPOLDMK4_2 {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 2;
		};
	};
	
	class rhsusf_acc_premier_anpvs27 : rhsusf_acc_premier {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 2;
		};
	};
	
	class rhsusf_acc_ACOG_MDO : ItemCore {
		class ItemInfo : InventoryOpticsItem_Base_F {
			opticType = 1;
		};
	};
	class Uniform_Base;	// External class reference
	
	class rhs_uniform_g3_mc : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhs_uniform_g3_m81 : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class rhs_uniform_g3_tan : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class rhs_uniform_g3_rgr : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class rhs_uniform_g3_blk : Uniform_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.3;
	};
	
	class rhs_uniform_cu_ocp : Uniform_Base {
		asr_camouflage = 0.3;
	};
	class Vest_Camo_Base;	// External class reference
	
	class rhsusf_iotv_ocp_base : Vest_Camo_Base {
		asr_camouflage = 0.3;
	};
	
	class rhsusf_spc : rhsusf_iotv_ocp_base {
		asr_camouflage = 0.4;
	};
	class Rifle_Base_F;	// External class reference
	
	class Rifle_Short_Base_F : Rifle_Base_F {};
	class Rifle_Long_Base_F;	// External class reference
	class Pistol_Base_F;	// External class reference
	
	class RHSUSF_SAFE_BASE : Rifle_Base_F {
		class Safe : Mode_SemiAuto {
			minRangeProbab = 0;
			midRangeProbab = 0;
			maxRangeProbab = 0;
		};
	};
	class cannon_120mm;	// External class reference
	
	class rhs_weap_m256 : cannon_120mm {
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class autocannon_30mm_CTWS;	// External class reference
	
	class RHS_weap_M242BC : autocannon_30mm_CTWS {
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class LMG_M200;	// External class reference
	
	class rhs_weap_m240veh : LMG_M200 {
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class rhs_weap_M197;	// External class reference
	
	class rhs_weap_M230 : rhs_weap_M197 {
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class Cannon_30mm_Plane_CAS_02_F;	// External class reference
	
	class rhsusf_M61A2 : Cannon_30mm_Plane_CAS_02_F {
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_M320_Base_F : Pistol_Base_F {
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 4;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 4;
			minRange = 60;
			minRangeProbab = 0.45;
			midRange = 200;
			midRangeProbab = 0.65;
			maxRange = 400;
			maxRangeProbab = 0.01;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_XM2010_Base_F : Rifle_Base_F {
		modes[] = {"SemiAuto", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class arifle_MX_Base_F;	// External class reference
	class UGL_F;	// External class reference
	
	class rhs_weap_m4_Base : arifle_MX_Base_F {
		modes[] = {"Single", "Burst3", "AI_Single_optics1", "AI_Single_optics2", "AI_far"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 20;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 700;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 900;
			maxRangeProbab = 0.1;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		
		class AI_far : Single {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 5;
			reloadtime = 0.2;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 4;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 600;
			midRangeProbab = 0.05;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
		
		class M203_GL : UGL_F {
			class Single : Mode_SemiAuto {
				aiRateOfFire = 4;
				aiRateOfFireDistance = 50;
				aiRateOfFireDispersion = 4;
				minRange = 60;
				minRangeProbab = 0.45;
				midRange = 200;
				midRangeProbab = 0.65;
				maxRange = 400;
				maxRangeProbab = 0.01;
			};
		};
		
		class M320_GL : M203_GL {
			class Single : Mode_SemiAuto {
				aiRateOfFire = 4;
				aiRateOfFireDistance = 50;
				aiRateOfFireDispersion = 4;
				minRange = 60;
				minRangeProbab = 0.45;
				midRange = 200;
				midRangeProbab = 0.65;
				maxRange = 400;
				maxRangeProbab = 0.01;
			};
		};
	};
	
	class rhs_weap_m4a1 : rhs_weap_m4_Base {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2", "AI_far"};
	};
	
	class rhs_weap_m4a1_blockII : rhs_weap_m4a1 {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2", "AI_far"};
	};
	
	class rhs_weap_mk18 : rhs_weap_m4a1_blockII {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 30;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 15;
			midRangeProbab = 0.7;
			maxRange = 30;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 120;
			minRangeProbab = 0.8;
			midRange = 200;
			midRangeProbab = 0.6;
			maxRange = 600;
			maxRangeProbab = 0.01;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 250;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 30;
			midRangeProbab = 0.8;
			maxRange = 60;
			maxRangeProbab = 0.1;
			showToPlayer = 1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
		};
	};
	
	class rhs_weap_m16a4 : rhs_weap_m4_Base {
		modes[] = {"Single", "Burst3", "AI_Single_optics1", "AI_Single_optics2", "AI_far"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 20;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 700;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 4;
			minRange = 200;
			minRangeProbab = 0.8;
			midRange = 300;
			midRangeProbab = 0.6;
			maxRange = 900;
			maxRangeProbab = 0.1;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 20;
			midRangeProbab = 0.8;
			maxRange = 40;
			maxRangeProbab = 0.1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
			textureType = "dual";
		};
		
		class AI_far : Single {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 5;
			reloadtime = 0.2;
			aiRateOfFire = 5;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 4;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 600;
			midRangeProbab = 0.05;
			maxRange = 800;
			maxRangeProbab = 0.01;
		};
	};
	
	class rhs_weap_hk416d10 : rhs_weap_m4a1 {
		modes[] = {"Single", "FullAuto", "AI_Burst_close", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 30;
			minRangeProbab = 0.7;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 15;
			midRangeProbab = 0.7;
			maxRange = 30;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
			aiRateOfFireDispersion = 3;
			minRange = 120;
			minRangeProbab = 0.8;
			midRange = 200;
			midRangeProbab = 0.6;
			maxRange = 600;
			maxRangeProbab = 0.01;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 250;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.04;
		};
		
		class Burst3 : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.2;
			midRange = 30;
			midRangeProbab = 0.8;
			maxRange = 60;
			maxRangeProbab = 0.1;
			showToPlayer = 1;
			burst = 3;
			displayName = $STR_DN_MODE_BURST;
			textureType = "burst";
			soundBurst = 0;
		};
		
		class Burst2 : Burst3 {
			burst = 2;
		};
	};
	
	class rhs_weap_m27iar : rhs_weap_m4a1 {
		modes[] = {"Single", "FullAuto", "AI_long", "AI_close", "AI_short", "AI_medium", "AI_far", "AI_far_optic1", "AI_far_optic2"};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.1;
		};
		
		class AI_long : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 0.5;
			minRange = 10;
			minRangeProbab = 0.1;
			midRange = 25;
			midRangeProbab = 0.8;
			maxRange = 50;
			maxRangeProbab = 0.1;
		};
		
		class AI_close : AI_long {
			burst = 8;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 25;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.8;
			maxRange = 100;
			maxRangeProbab = 0.1;
		};
		
		class AI_short : AI_close {
			burst = 5;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 200;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
		};
		
		class AI_medium : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 100;
			minRangeProbab = 0.1;
			midRange = 200;
			midRangeProbab = 0.8;
			maxRange = 400;
			maxRangeProbab = 0.1;
		};
		
		class AI_far : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 200;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_toofar : AI_far {
			burst = 5;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 2;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 800;
			midRangeProbab = 0.2;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_far_optic1 : AI_far {
			requiredOpticType = 1;
			burst = 3;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 1;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 800;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.2;
		};
		
		class AI_toofar_optic1 : AI_far_optic1 {
			burst = 2;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 2;
			minRange = 800;
			minRangeProbab = 0.4;
			midRange = 1200;
			midRangeProbab = 0.6;
			maxRange = 1600;
			maxRangeProbab = 0.1;
		};
		
		class AI_far_optic2 : AI_far_optic1 {
			requiredOpticType = 2;
		};
		
		class AI_toofar_optic2 : AI_toofar_optic1 {
			requiredOpticType = 2;
		};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 300;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.1;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
	};
	class LMG_Mk200_F;	// External class reference
	
	class rhs_weap_M249_base : LMG_Mk200_F {
		modes[] = {"FullAuto", "AI_long", "AI_close", "AI_short", "AI_medium", "AI_far", "AI_toofar", "AI_far_optic1", "AI_toofar_optic1", "AI_far_optic2", "AI_toofar_optic2"};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.1;
		};
		
		class AI_long : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 0.5;
			minRange = 10;
			minRangeProbab = 0.1;
			midRange = 25;
			midRangeProbab = 0.8;
			maxRange = 50;
			maxRangeProbab = 0.1;
		};
		
		class AI_close : AI_long {
			burst = 8;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 25;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.8;
			maxRange = 100;
			maxRangeProbab = 0.1;
		};
		
		class AI_short : AI_close {
			burst = 5;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 200;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
		};
		
		class AI_medium : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 100;
			minRangeProbab = 0.1;
			midRange = 200;
			midRangeProbab = 0.8;
			maxRange = 400;
			maxRangeProbab = 0.1;
		};
		
		class AI_far : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 200;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_toofar : AI_far {
			burst = 5;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 2;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 800;
			midRangeProbab = 0.2;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_far_optic1 : AI_far {
			requiredOpticType = 1;
			burst = 3;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 1;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 800;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.2;
		};
		
		class AI_toofar_optic1 : AI_far_optic1 {
			burst = 2;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 2;
			minRange = 800;
			minRangeProbab = 0.4;
			midRange = 1200;
			midRangeProbab = 0.6;
			maxRange = 1600;
			maxRangeProbab = 0.1;
		};
		
		class AI_far_optic2 : AI_far_optic1 {
			requiredOpticType = 2;
		};
		
		class AI_toofar_optic2 : AI_toofar_optic1 {
			requiredOpticType = 2;
		};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 300;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.1;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_saw_base : Rifle_Base_F {
		modes[] = {"FullAuto", "AI_long", "AI_close", "AI_short", "AI_medium", "AI_far", "AI_toofar", "AI_far_optic1", "AI_toofar_optic1", "AI_far_optic2", "AI_toofar_optic2"};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.1;
		};
		
		class AI_long : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 0.5;
			minRange = 10;
			minRangeProbab = 0.1;
			midRange = 25;
			midRangeProbab = 0.8;
			maxRange = 50;
			maxRangeProbab = 0.1;
		};
		
		class AI_close : AI_long {
			burst = 8;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 25;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.8;
			maxRange = 100;
			maxRangeProbab = 0.1;
		};
		
		class AI_short : AI_close {
			burst = 5;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 200;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
		};
		
		class AI_medium : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 100;
			minRangeProbab = 0.1;
			midRange = 200;
			midRangeProbab = 0.8;
			maxRange = 400;
			maxRangeProbab = 0.1;
		};
		
		class AI_far : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 200;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_toofar : AI_far {
			burst = 5;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 2;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 800;
			midRangeProbab = 0.2;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_far_optic1 : AI_far {
			requiredOpticType = 1;
			burst = 3;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 1;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 800;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.2;
		};
		
		class AI_toofar_optic1 : AI_far_optic1 {
			burst = 2;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 2;
			minRange = 800;
			minRangeProbab = 0.4;
			midRange = 1200;
			midRangeProbab = 0.6;
			maxRange = 1600;
			maxRangeProbab = 0.1;
		};
		
		class AI_far_optic2 : AI_far_optic1 {
			requiredOpticType = 2;
		};
		
		class AI_toofar_optic2 : AI_toofar_optic1 {
			requiredOpticType = 2;
		};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 300;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.1;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_lmg_minimipara : rhs_weap_saw_base {
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.1;
		};
		
		class AI_long : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 0.5;
			minRange = 10;
			minRangeProbab = 0.1;
			midRange = 25;
			midRangeProbab = 0.8;
			maxRange = 50;
			maxRangeProbab = 0.1;
		};
		
		class AI_close : AI_long {
			burst = 8;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 25;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.8;
			maxRange = 100;
			maxRangeProbab = 0.1;
		};
		
		class AI_short : AI_close {
			burst = 5;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 200;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
		};
		
		class AI_medium : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 100;
			minRangeProbab = 0.1;
			midRange = 200;
			midRangeProbab = 0.8;
			maxRange = 400;
			maxRangeProbab = 0.1;
		};
		
		class AI_far : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 200;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_toofar : AI_far {
			burst = 5;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 2;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 800;
			midRangeProbab = 0.2;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_far_optic1 : AI_far {
			requiredOpticType = 1;
			burst = 3;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 1;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 800;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.2;
		};
		
		class AI_toofar_optic1 : AI_far_optic1 {
			burst = 2;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 2;
			minRange = 800;
			minRangeProbab = 0.4;
			midRange = 1200;
			midRangeProbab = 0.6;
			maxRange = 1600;
			maxRangeProbab = 0.1;
		};
		
		class AI_far_optic2 : AI_far_optic1 {
			requiredOpticType = 2;
		};
		
		class AI_toofar_optic2 : AI_toofar_optic1 {
			requiredOpticType = 2;
		};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 300;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.1;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
	};
	
	class rhs_weap_m240_base : rhs_weap_M249_base {
		modes[] = {"manual", "AI_long", "AI_close", "AI_short", "AI_medium", "AI_far", "AI_toofar", "AI_far_optic1", "AI_toofar_optic1", "AI_far_optic2", "AI_toofar_optic2"};
		
		class manual : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 20;
			maxRangeProbab = 0.1;
		};
		
		class AI_long : manual {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 0.5;
			minRange = 10;
			minRangeProbab = 0.1;
			midRange = 25;
			midRangeProbab = 0.8;
			maxRange = 50;
			maxRangeProbab = 0.1;
		};
		
		class AI_close : AI_long {
			burst = 8;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 25;
			minRangeProbab = 0.1;
			midRange = 50;
			midRangeProbab = 0.8;
			maxRange = 100;
			maxRangeProbab = 0.1;
		};
		
		class AI_short : AI_close {
			burst = 5;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 200;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.1;
			midRange = 100;
			midRangeProbab = 0.8;
			maxRange = 200;
			maxRangeProbab = 0.1;
		};
		
		class AI_medium : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 100;
			minRangeProbab = 0.1;
			midRange = 200;
			midRangeProbab = 0.8;
			maxRange = 400;
			maxRangeProbab = 0.1;
		};
		
		class AI_far : AI_close {
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 1;
			minRange = 200;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_toofar : AI_far {
			burst = 5;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 2;
			minRange = 400;
			minRangeProbab = 0.1;
			midRange = 800;
			midRangeProbab = 0.2;
			maxRange = 1000;
			maxRangeProbab = 0.01;
		};
		
		class AI_far_optic1 : AI_far {
			requiredOpticType = 1;
			burst = 3;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 800;
			aiRateOfFireDispersion = 1;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 800;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.2;
		};
		
		class AI_toofar_optic1 : AI_far_optic1 {
			burst = 2;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 2;
			minRange = 800;
			minRangeProbab = 0.4;
			midRange = 1200;
			midRangeProbab = 0.6;
			maxRange = 1600;
			maxRangeProbab = 0.1;
		};
		
		class AI_far_optic2 : AI_far_optic1 {
			requiredOpticType = 2;
		};
		
		class AI_toofar_optic2 : AI_toofar_optic1 {
			requiredOpticType = 2;
		};
		
		class Single : manual {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 300;
			minRangeProbab = 0.1;
			midRange = 400;
			midRangeProbab = 0.1;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class srifle_EBR_F;	// External class reference
	
	class rhs_weap_m14ebrri : srifle_EBR_F {
		modes[] = {"SemiAuto", "AI_Single_optics1", "AI_Single_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
	};
	
	class rhs_weap_sr25 : rhs_weap_m14ebrri {
		class Single : Mode_SemiAuto {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 350;
			aiRateOfFireDispersion = 2;
			minRange = 15;
			minRangeProbab = 0.8;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class FullAuto : Mode_FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 1;
			midRangeProbab = 0.8;
			maxRange = 5;
			maxRangeProbab = 0.1;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 5;
			minRangeProbab = 0.8;
			midRange = 10;
			midRangeProbab = 0.7;
			maxRange = 15;
			maxRangeProbab = 0.2;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 3;
			aiRateOfFireDistance = 550;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.9;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 800;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 6;
			aiRateOfFireDistance = 1200;
			aiRateOfFireDispersion = 4;
			minRange = 150;
			minRangeProbab = 0.7;
			midRange = 500;
			midRangeProbab = 0.8;
			maxRange = 1200;
			maxRangeProbab = 0.05;
		};
		
		class SemiAuto : Single {
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 2;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 150;
			midRangeProbab = 0.5;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
	};
	class GM6_base_F;	// External class reference
	
	class rhs_weap_M107_Base_F : GM6_base_F {
		modes[] = {"Single", "AI_Single_optics1", "AI_Single_optics2", "AI_Single_far_optics2"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 3;
			aiRateOfFireDistance = 400;
			aiRateOfFireDispersion = 2;
			minRange = 1;
			minRangeProbab = 0.4;
			midRange = 150;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics1 : Single {
			showToPlayer = 0;
			requiredOpticType = 1;
			aiRateOfFire = 4;
			aiRateOfFireDistance = 600;
			aiRateOfFireDispersion = 3;
			minRange = 150;
			minRangeProbab = 0.2;
			midRange = 500;
			midRangeProbab = 0.7;
			maxRange = 1000;
			maxRangeProbab = 0.1;
		};
		
		class AI_Single_optics2 : AI_Single_optics1 {
			requiredOpticType = 2;
			aiRateOfFire = 8;
			aiRateOfFireDistance = 1100;
			aiRateOfFireDispersion = 4;
			minRange = 250;
			minRangeProbab = 0.2;
			midRange = 750;
			midRangeProbab = 0.7;
			maxRange = 1500;
			maxRangeProbab = 0.4;
		};
		
		class AI_Single_far_optics2 : AI_Single_optics2 {
			aiRateOfFire = 10;
			aiRateOfFireDistance = 1500;
			aiRateOfFireDispersion = 5;
			minRange = 500;
			minRangeProbab = 0.3;
			midRange = 1200;
			midRangeProbab = 0.7;
			maxRange = 2500;
			maxRangeProbab = 0.1;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class rhs_weap_M590_5RD : Rifle_Base_F {
		class Single : Mode_SemiAuto {
			minRange = 0;
			minRangeProbab = 0.7;
			midRange = 50;
			midRangeProbab = 0.6;
			maxRange = 150;
			maxRangeProbab = 0.02;
		};
	};
	
	class rhs_weap_m32_Base_F : Rifle_Base_F {
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			aiRateOfFire = 4;
			aiRateOfFireDistance = 50;
			aiRateOfFireDispersion = 4;
			minRange = 60;
			minRangeProbab = 0.45;
			midRange = 200;
			midRangeProbab = 0.65;
			maxRange = 400;
			maxRangeProbab = 0.01;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	
	class SMG_02_base_F : Rifle_Short_Base_F {
		class Single;	// External class reference
		class FullAuto;	// External class reference
	};
	
	class rhsusf_weap_MP7A1_base_f : SMG_02_base_F {
		modes[] = {"Single", "FullAuto", "AI_Burst_close"};
		
		class Single : Single {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 300;
			aiRateOfFireDispersion = 1;
			minRange = 50;
			minRangeProbab = 0.9;
			midRange = 80;
			midRangeProbab = 0.5;
			maxRange = 300;
			maxRangeProbab = 0.01;
		};
		
		class FullAuto : FullAuto {
			aiRateOfFire = 0.1;
			aiRateOfFireDistance = 50;
			minRange = 0;
			minRangeProbab = 0.9;
			midRange = 10;
			midRangeProbab = 0.8;
			maxRange = 20;
			maxRangeProbab = 0.4;
		};
		
		class AI_Burst_close : FullAuto {
			showToPlayer = 0;
			aiBurstTerminable = 1;
			burst = 4;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 0.5;
			minRange = 20;
			minRangeProbab = 0.8;
			midRange = 30;
			midRangeProbab = 0.5;
			maxRange = 60;
			maxRangeProbab = 0.4;
		};
		aiDispersionCoefX = 6;
		aiDispersionCoefY = 8;
	};
	class Launcher_Base_F;	// External class reference
	
	class rhs_weap_M136 : Launcher_Base_F {
		minRange = 10;
		minRangeProbab = 0.3;
		midRange = 200;
		midRangeProbab = 0.8;
		maxRange = 400;
		maxRangeProbab = 0.1;
	};
	class hgun_ACPC2_F;	// External class reference
	
	class rhsusf_weap_m1911a1 : hgun_ACPC2_F {
		class Single : Mode_SemiAuto {
			aiRateOfFire = 1;
			aiRateOfFireDistance = 100;
			aiRateOfFireDispersion = 1;
			minRange = 0;
			minRangeProbab = 0.1;
			midRange = 30;
			midRangeProbab = 0.05;
			maxRange = 70;
			maxRangeProbab = 0.01;
		};
	};
};
