// config.bin - 11:34:20 08/29/17, generated in 0.72 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgAddons.hpp"
#include "Mode_SemiAuto.hpp"
#include "Mode_Burst.hpp"
#include "Mode_FullAuto.hpp"
#include "CfgWeapons.hpp"
