// Generated by unRap v1.06 by Kegetys

class Mode_Burst : Mode_SemiAuto {
	aiRateOfFire = 1;
	aiRateOfFireDistance = 100;
	aiRateOfFireDispersion = 0.5;
	minRange = 5;
	minRangeProbab = 0.8;
	midRange = 10;
	midRangeProbab = 0.7;
	maxRange = 20;
	maxRangeProbab = 0.2;
	aiDispersionCoefX = 6;
	aiDispersionCoefY = 8;
};
