// Generated by unRap v1.06 by Kegetys

class Mode_FullAuto : Mode_SemiAuto {
	aiRateOfFire = 0.1;
	aiRateOfFireDistance = 50;
	minRange = 0;
	minRangeProbab = 0.9;
	midRange = 1;
	midRangeProbab = 0.8;
	maxRange = 5;
	maxRangeProbab = 0.1;
	aiDispersionCoefX = 6;
	aiDispersionCoefY = 8;
};
