// Generated by unRap v1.06 by Kegetys

class Mode_SemiAuto {
	aiRateOfFire = 1;
	aiRateOfFireDistance = 300;
	aiRateOfFireDispersion = 2;
	minRange = 0;
	minRangeProbab = 0.9;
	midRange = 150;
	midRangeProbab = 0.5;
	maxRange = 500;
	maxRangeProbab = 0.1;
	aiDispersionCoefX = 6;
	aiDispersionCoefY = 8;
};
