// Generated by unRap v1.06 by Kegetys

class CfgGroups {
	class Indep {
		class IND_F {
			class SpecOps {
				class asdg_HAF_reconTeam {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_reconTeam0";
					side = 2;
					faction = IND_F;
					
					class Unit0 {
						side = 2;
						vehicle = "asdg_I_recon_TL";
						rank = SERGEANT;
						position[] = {0, 0, 0};
					};
					
					class Unit1 {
						side = 2;
						vehicle = "asdg_I_recon_M";
						rank = CORPORAL;
						position[] = {5, -5, 0};
					};
					
					class Unit2 {
						side = 2;
						vehicle = "asdg_I_recon_medic";
						rank = PRIVATE;
						position[] = {-5, -5, 0};
					};
					
					class Unit3 {
						side = 2;
						vehicle = "asdg_I_recon";
						rank = CORPORAL;
						position[] = {10, -10, 0};
					};
					
					class Unit4 {
						side = 2;
						vehicle = "asdg_I_recon_MG";
						rank = PRIVATE;
						position[] = {-10, -10, 0};
					};
					
					class Unit5 {
						side = 2;
						vehicle = "asdg_I_recon_exp";
						rank = PRIVATE;
						position[] = {15, -15, 0};
					};
				};
				
				class asdg_HAF_reconPatrol {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_reconPatrol0";
					side = 2;
					faction = IND_F;
					
					class Unit0 {
						side = 2;
						vehicle = "asdg_I_recon_TL";
						rank = SERGEANT;
						position[] = {0, 0, 0};
					};
					
					class Unit1 {
						side = 2;
						vehicle = "asdg_I_recon_M";
						rank = CORPORAL;
						position[] = {5, -5, 0};
					};
					
					class Unit2 {
						side = 2;
						vehicle = "asdg_I_recon_medic";
						rank = PRIVATE;
						position[] = {-5, -5, 0};
					};
					
					class Unit3 {
						side = 2;
						vehicle = "asdg_I_recon";
						rank = PRIVATE;
						position[] = {10, -10, 0};
					};
				};
				
				class asdg_HAF_reconSentry {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_reconSentry0";
					side = 2;
					faction = IND_F;
					
					class Unit0 {
						side = 2;
						vehicle = "asdg_I_recon_M";
						rank = CORPORAL;
						position[] = {0, 0, 0};
					};
					
					class Unit1 {
						side = 2;
						vehicle = "asdg_I_recon";
						rank = PRIVATE;
						position[] = {5, -5, 0};
					};
				};
			};
		};
	};
};
