// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_greenrico {
		units[] = {"asdg_I_AssaultPack_dgtl_AR", "asdg_I_recon", "asdg_I_recon_exp", "asdg_I_recon_medic", "asdg_I_recon_TL", "asdg_I_recon_M", "asdg_I_recon_MG"};
		weapons[] = {"asdg_LMG_03_F_ARCO_LP", "asdg_DMR_06_DMS_BI"};
		requiredVersion = 1.66;
		requiredAddons[] = {"A3_Characters_F", "A3_Weapons_F", "A3_Weapons_F_Mark", "A3_Weapons_F_Exp"};
		version = 1.1.0.98;
		author = "Robalo";
	};
};
