// Generated by unRap v1.06 by Kegetys

class CfgWeapons {
	class LMG_03_F;	// External class reference
	
	class asdg_LMG_03_F_ARCO_LP : LMG_03_F {
		class LinkedItems {
			class LinkedItemsOptic {
				slot = "CowsSlot";
				item = "optic_Arco_blk_F";
			};
			
			class LinkedItemsAcc {
				slot = "PointerSlot";
				item = "acc_pointer_IR";
			};
		};
	};
	class srifle_DMR_06_olive_F;	// External class reference
	
	class asdg_DMR_06_DMS_BI : srifle_DMR_06_olive_F {
		class LinkedItems {
			class LinkedItemsOptic {
				slot = "CowsSlot";
				item = "optic_DMS";
			};
			
			class LinkedItemsUnder {
				slot = "UnderBarrelSlot";
				item = "bipod_03_F_oli";
			};
		};
	};
	class arifle_SPAR_01_blk_F;	// External class reference
	
	class arifle_SPAR_01_blk_ERCO_Pointer_F : arifle_SPAR_01_blk_F {
		class LinkedItems {
			class LinkedItemsOptic;	// External class reference
		};
	};
	
	class asdg_SPAR_01_blk_MRCO_LP : arifle_SPAR_01_blk_ERCO_Pointer_F {
		class LinkedItems : LinkedItems {
			class LinkedItemsOptic : LinkedItemsOptic {
				item = "optic_MRCO";
			};
		};
	};
	class arifle_SPAR_01_blk_ACO_Pointer_F;	// External class reference
	
	class asdg_SPAR_01_blk_HWS : arifle_SPAR_01_blk_ACO_Pointer_F {
		class LinkedItems {
			class LinkedItemsOptic {
				slot = "CowsSlot";
				item = "optic_Holosight_blk_F";
			};
		};
	};
	class arifle_SPAR_01_GL_blk_F;	// External class reference
	
	class arifle_SPAR_01_GL_blk_ERCO_Pointer_F : arifle_SPAR_01_GL_blk_F {
		class LinkedItems {
			class LinkedItemsOptic;	// External class reference
		};
	};
	
	class asdg_SPAR_01_GL_blk_MRCO_LP : arifle_SPAR_01_GL_blk_ERCO_Pointer_F {
		class LinkedItems : LinkedItems {
			class LinkedItemsOptic : LinkedItemsOptic {
				item = "optic_MRCO";
			};
		};
	};
};
