// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class All {
		class SpeechVariants {
			class Default {
				speechSingular[] = {};
				speechPlural[] = {};
			};
		};
		textSingular = "";
		textPlural = "";
		nameSound = "";
	};
	class Man;	// External class reference
	
	class CAManBase : Man {
		asr_ai_level = 6;
		audible = 0.025;
		crouchProbabilityCombat = 0.8;
		crouchProbabilityEngage = 0.9;
		minFireTime = 10;
		spotableDarkNightLightsOff = 0.0015;
		spotableNightLightsOff = 0.0175;
	};
	
	class Civilian : CAManBase {
		asr_ai_level = 7;
		accuracy = 0.2;
		primaryAmmoCoef = 0;
		secondaryAmmoCoef = 0;
		handgunAmmoCoef = 0;
	};
	class C_man_1;	// External class reference
	
	class C_man_pilot_F : C_man_1 {
		asr_ai_level = 9;
	};
	
	class SoldierWB : CAManBase {
		fsmDanger = "x\asr_ai3\addons\main\danger.fsm";
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class SoldierEB : CAManBase {
		fsmDanger = "x\asr_ai3\addons\main\danger.fsm";
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class SoldierGB : CAManBase {
		fsmDanger = "x\asr_ai3\addons\main\danger.fsm";
		asr_ai_level = 4;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class B_Soldier_base_F : SoldierWB {
		minFireTime = 10;
	};
	class B_Soldier_02_f;	// External class reference
	class B_Soldier_03_f;	// External class reference
	class B_Soldier_04_f;	// External class reference
	class B_Soldier_05_f;	// External class reference
	
	class B_Soldier_SL_F : B_Soldier_03_f {
		asr_ai_level = 3;
	};
	
	class B_Soldier_TL_F : B_Soldier_03_f {
		asr_ai_level = 3;
	};
	
	class B_soldier_M_F : B_Soldier_base_F {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class B_Sharpshooter_F : B_Soldier_base_F {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class B_Helipilot_F : B_Soldier_04_f {
		asr_ai_level = 8;
	};
	
	class B_Pilot_F : B_Soldier_05_f {
		asr_ai_level = 8;
	};
	
	class B_Story_Pilot_F : B_Soldier_base_F {
		asr_ai_level = 8;
	};
	
	class B_Soldier_diver_base_F : B_Soldier_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class B_Soldier_sniper_base_F : B_Soldier_base_F {
		asr_ai_level = 10;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class B_spotter_F : B_Soldier_sniper_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class B_Soldier_recon_base : B_Soldier_base_F {
		asr_ai_level = 2;
	};
	
	class B_recon_M_F : B_Soldier_recon_base {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class B_Story_SF_Captain_F : B_Soldier_02_f {
		asr_ai_level = 1;
	};
	
	class B_CTRG_soldier_GL_LAT_F : B_Soldier_base_F {
		asr_ai_level = 1;
	};
	
	class B_CTRG_soldier_engineer_exp_F : B_Soldier_02_f {
		asr_ai_level = 1;
	};
	
	class B_CTRG_soldier_M_medic_F : B_Soldier_03_f {
		asr_ai_level = 1;
	};
	
	class B_CTRG_soldier_AR_A_F : B_Soldier_03_f {
		asr_ai_level = 1;
	};
	
	class B_CTRG_Sharphooter_F : B_Soldier_base_F {
		asr_ai_level = 1;
	};
	class B_G_Soldier_F;	// External class reference
	
	class B_CTRG_Soldier_base_F : B_Soldier_base_F {
		asr_ai_level = 1;
	};
	class B_GEN_Soldier_base_F;	// External class reference
	
	class B_GEN_Commander_F : B_GEN_Soldier_base_F {
		asr_ai_level = 3;
	};
	
	class I_G_Soldier_base_F : SoldierGB {
		asr_ai_level = 6;
		minFireTime = 10;
	};
	
	class I_G_Soldier_SL_F : I_G_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_G_Soldier_TL_F : I_G_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_G_Story_Protagonist_F : B_G_Soldier_F {
		asr_ai_level = 5;
	};
	
	class I_G_Soldier_M_F : I_G_Soldier_base_F {
		asr_ai_level = 5;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class I_G_Sharpshooter_F : I_G_Soldier_base_F {
		asr_ai_level = 5;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class I_G_officer_F : I_G_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_G_Story_SF_Captain_F : B_G_Soldier_F {
		asr_ai_level = 1;
	};
	class I_C_Soldier_base_F;	// External class reference
	
	class I_C_Soldier_Para_1_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_2_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_3_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_4_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_5_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
		secondaryAmmoCoef = 0.5;
	};
	
	class I_C_Soldier_Para_6_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_7_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Para_8_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Soldier_Bandit_2_F : I_C_Soldier_base_F {
		secondaryAmmoCoef = 0.5;
	};
	
	class I_C_Soldier_Camo_F : I_C_Soldier_base_F {
		asr_ai_level = 5;
	};
	
	class I_C_Pilot_F : I_C_Soldier_base_F {
		asr_ai_level = 9;
	};
	
	class I_C_Helipilot_F : I_C_Soldier_base_F {
		asr_ai_level = 9;
	};
	
	class I_Soldier_base_F : SoldierGB {
		minFireTime = 10;
	};
	class I_Soldier_02_F;	// External class reference
	class I_Soldier_03_F;	// External class reference
	class I_Soldier_04_F;	// External class reference
	
	class I_Soldier_SL_F : I_Soldier_02_F {
		asr_ai_level = 3;
	};
	
	class I_Soldier_TL_F : I_Soldier_base_F {
		asr_ai_level = 3;
	};
	
	class I_Soldier_M_F : I_Soldier_base_F {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class I_helipilot_F : I_Soldier_03_F {
		asr_ai_level = 8;
	};
	
	class I_pilot_F : I_Soldier_04_F {
		asr_ai_level = 8;
	};
	
	class I_Soldier_sniper_base_F : I_Soldier_base_F {
		asr_ai_level = 10;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class I_Spotter_F : I_Soldier_sniper_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class I_Soldier_diver_base_F : I_Soldier_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_Soldier_base_F : SoldierEB {
		minFireTime = 10;
	};
	class O_Soldier_02_F;	// External class reference
	class O_Soldier_Urban_base;	// External class reference
	
	class O_Soldier_SL_F : O_Soldier_base_F {
		asr_ai_level = 3;
	};
	
	class O_Soldier_TL_F : O_Soldier_base_F {
		asr_ai_level = 3;
	};
	
	class O_soldierU_TL_F : O_Soldier_Urban_base {
		asr_ai_level = 3;
	};
	
	class O_SoldierU_SL_F : O_Soldier_Urban_base {
		asr_ai_level = 3;
	};
	
	class O_soldier_M_F : O_Soldier_base_F {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_soldierU_M_F : O_Soldier_Urban_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_Sharpshooter_F : O_Soldier_base_F {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_Urban_Sharpshooter_F : O_Soldier_Urban_base {
		asr_ai_level = 3;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_helipilot_F : O_Soldier_02_F {
		asr_ai_level = 8;
	};
	
	class O_Soldier_diver_base_F : O_Soldier_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_Soldier_sniper_base_F : O_Soldier_base_F {
		asr_ai_level = 10;
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_spotter_F : O_Soldier_sniper_base_F {
		asr_ai_level = 2;
		primaryAmmoCoef = 0.4;
		secondaryAmmoCoef = 0.2;
		handgunAmmoCoef = 0.01;
	};
	
	class O_Soldier_recon_base : O_Soldier_base_F {
		asr_ai_level = 2;
	};
	
	class O_recon_M_F : O_Soldier_recon_base {
		primaryAmmoCoef = 0.3;
		secondaryAmmoCoef = 0.01;
		handgunAmmoCoef = 0.1;
	};
	
	class O_V_Soldier_Viper_F : O_Soldier_base_F {
		asr_ai_level = 1;
	};
	
	class O_V_Soldier_base_F : O_Soldier_base_F {
		asr_ai_level = 1;
	};
	
	class B_UAV_AI : B_Helipilot_F {
		asr_ai_level = 0;
	};
	
	class O_UAV_AI : O_helipilot_F {
		asr_ai_level = 0;
	};
	
	class I_UAV_AI : O_UAV_AI {
		asr_ai_level = 0;
	};
};
