// config.bin - 11:34:12 08/29/17, generated in 0.05 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgAddons.hpp"
#include "CfgVehicles.hpp"
