// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class asr_ai3_cfgcamouflage {
		addonRootClass = "A3_Characters_F";
		units[] = {};
		weapons[] = {};
		ammo[] = {};
		requiredAddons[] = {"A3_Characters_F", "A3_Characters_F_Mark", "A3_Characters_F_Exp", "A3_Weapons_F", "A3_Weapons_F_Mark", "A3_Weapons_F_Exp"};
		requiredVersion = 1.7;
		author = "Robalo";
	};
};
