// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class B_AssaultPack_Base;	// External class reference
	
	class B_AssaultPack_khk : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_AssaultPack_dgtl : B_AssaultPack_Base {
		asr_camouflage = 0.8;
	};
	
	class B_AssaultPack_rgr : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_AssaultPack_sgg : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_AssaultPack_blk : B_AssaultPack_Base {
		asr_camouflage = 1.0;
		asr_camouflage_night = 0.8;
	};
	
	class B_AssaultPack_cbr : B_AssaultPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_AssaultPack_mcamo : B_AssaultPack_Base {
		asr_camouflage = 0.8;
	};
	
	class B_AssaultPack_ocamo : B_AssaultPack_Base {
		asr_camouflage = 0.8;
	};
	class B_Kitbag_Base;	// External class reference
	
	class B_Kitbag_rgr : B_Kitbag_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Kitbag_mcamo : B_Kitbag_Base {
		asr_camouflage = 0.9;
	};
	
	class B_Kitbag_sgg : B_Kitbag_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Kitbag_cbr : B_Kitbag_Base {
		asr_camouflage = 1.0;
	};
	class B_TacticalPack_Base;	// External class reference
	
	class B_TacticalPack_rgr : B_TacticalPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_TacticalPack_mcamo : B_TacticalPack_Base {
		asr_camouflage = 0.8;
	};
	
	class B_TacticalPack_ocamo : B_TacticalPack_Base {
		asr_camouflage = 0.8;
	};
	
	class B_TacticalPack_blk : B_TacticalPack_Base {
		asr_camouflage = 1.0;
		asr_camouflage_night = 0.8;
	};
	
	class B_TacticalPack_oli : B_TacticalPack_Base {
		asr_camouflage = 0.9;
	};
	class B_FieldPack_Base;	// External class reference
	
	class B_FieldPack_khk : B_FieldPack_Base {
		asr_camouflage = 1.0;
	};
	
	class B_FieldPack_ocamo : B_FieldPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_FieldPack_oucamo : B_FieldPack_Base {
		asr_camouflage = 0.9;
	};
	
	class B_FieldPack_cbr : B_FieldPack_Base {
		asr_camouflage = 1.0;
	};
	
	class B_FieldPack_blk : B_FieldPack_Base {
		asr_camouflage = 1.1;
		asr_camouflage_night = 0.9;
	};
	class B_Carryall_Base;	// External class reference
	
	class B_Carryall_ocamo : B_Carryall_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Carryall_oucamo : B_Carryall_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Carryall_mcamo : B_Carryall_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Carryall_khk : B_Carryall_Base {
		asr_camouflage = 1.1;
	};
	
	class B_Carryall_cbr : B_Carryall_Base {
		asr_camouflage = 1.1;
	};
	class B_Bergen_Base;	// External class reference
	
	class B_Bergen_sgg : B_Bergen_Base {
		asr_camouflage = 1.2;
	};
	
	class B_Bergen_mcamo : B_Bergen_Base {
		asr_camouflage = 1.1;
	};
	
	class B_Bergen_rgr : B_Bergen_Base {
		asr_camouflage = 1.2;
	};
	
	class B_Bergen_blk : B_Bergen_Base {
		asr_camouflage = 1.3;
		asr_camouflage_night = 1.1;
	};
	
	class B_FieldPack_oli : B_FieldPack_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Carryall_oli : B_Carryall_Base {
		asr_camouflage = 1.1;
	};
	
	class B_AssaultPack_Kerry : B_AssaultPack_mcamo {
		asr_camouflage = 0.9;
	};
	class B_Bergen_Base_F;	// External class reference
	
	class B_Bergen_mcamo_F : B_Bergen_Base_F {
		asr_camouflage = 1.1;
	};
	
	class B_Bergen_dgtl_F : B_Bergen_Base_F {
		asr_camouflage = 1.1;
	};
	
	class B_Bergen_hex_F : B_Bergen_Base_F {
		asr_camouflage = 1.1;
	};
	
	class B_Bergen_tna_F : B_Bergen_Base_F {
		asr_camouflage = 1.1;
	};
	
	class B_AssaultPack_tna_F : B_AssaultPack_Base {
		asr_camouflage = 0.8;
	};
	
	class B_Carryall_ghex_F : B_Carryall_Base {
		asr_camouflage = 1.0;
	};
	
	class B_FieldPack_ghex_F : B_FieldPack_Base {
		asr_camouflage = 0.9;
	};
	class B_ViperHarness_base_F;	// External class reference
	
	class B_ViperHarness_blk_F : B_ViperHarness_base_F {
		asr_camouflage = 1.0;
		asr_camouflage_night = 0.8;
	};
	
	class B_ViperHarness_ghex_F : B_ViperHarness_base_F {
		asr_camouflage = 0.8;
	};
	
	class B_ViperHarness_hex_F : B_ViperHarness_base_F {
		asr_camouflage = 0.8;
	};
	
	class B_ViperHarness_khk_F : B_ViperHarness_base_F {
		asr_camouflage = 0.9;
	};
	
	class B_ViperHarness_oli_F : B_ViperHarness_base_F {
		asr_camouflage = 0.9;
	};
	class B_ViperLightHarness_base_F;	// External class reference
	
	class B_ViperLightHarness_blk_F : B_ViperLightHarness_base_F {
		asr_camouflage = 1.0;
		asr_camouflage_night = 0.8;
	};
	
	class B_ViperLightHarness_ghex_F : B_ViperLightHarness_base_F {
		asr_camouflage = 0.8;
	};
	
	class B_ViperLightHarness_hex_F : B_ViperLightHarness_base_F {
		asr_camouflage = 0.8;
	};
	
	class B_ViperLightHarness_khk_F : B_ViperLightHarness_base_F {
		asr_camouflage = 0.9;
	};
	
	class B_ViperLightHarness_oli_F : B_ViperLightHarness_base_F {
		asr_camouflage = 0.9;
	};
	class Weapon_Bag_Base;	// External class reference
	class Bag_Base;	// External class reference
	
	class B_HMG_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_HMG_01_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_HMG_01_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_HMG_01_A_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 0.9;
	};
	
	class O_HMG_01_A_weapon_F : B_HMG_01_A_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_HMG_01_A_weapon_F : B_HMG_01_A_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_GMG_01_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 0.9;
	};
	
	class O_GMG_01_weapon_F : B_GMG_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_GMG_01_weapon_F : B_GMG_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_GMG_01_A_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 0.9;
	};
	
	class O_GMG_01_A_weapon_F : B_GMG_01_A_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_GMG_01_A_weapon_F : B_GMG_01_A_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_HMG_01_high_weapon_F : B_HMG_01_weapon_F {
		asr_camouflage = 0.9;
	};
	
	class O_HMG_01_high_weapon_F : B_HMG_01_high_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_HMG_01_high_weapon_F : B_HMG_01_high_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_GMG_01_high_weapon_F : B_HMG_01_high_weapon_F {
		asr_camouflage = 0.9;
	};
	
	class O_GMG_01_high_weapon_F : B_GMG_01_high_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_GMG_01_high_weapon_F : B_GMG_01_high_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_HMG_01_support_F : Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_HMG_01_support_F : B_HMG_01_support_F {
		asr_camouflage = 1.0;
	};
	
	class I_HMG_01_support_F : B_HMG_01_support_F {
		asr_camouflage = 1.0;
	};
	
	class B_HMG_01_support_high_F : B_HMG_01_support_F {
		asr_camouflage = 0.9;
	};
	
	class O_HMG_01_support_high_F : B_HMG_01_support_high_F {
		asr_camouflage = 1.0;
	};
	
	class I_HMG_01_support_high_F : B_HMG_01_support_high_F {
		asr_camouflage = 1.0;
	};
	
	class B_Mortar_01_support_F : Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_Mortar_01_support_F : B_Mortar_01_support_F {
		asr_camouflage = 1.0;
	};
	
	class I_Mortar_01_support_F : B_Mortar_01_support_F {
		asr_camouflage = 1.0;
	};
	
	class B_Mortar_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_Mortar_01_weapon_F : B_Mortar_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class I_Mortar_01_weapon_F : B_Mortar_01_weapon_F {
		asr_camouflage = 1.0;
	};
	
	class B_AA_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_AA_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 1.0;
	};
	
	class I_AA_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 1.0;
	};
	
	class B_AT_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.9;
	};
	
	class O_AT_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 1.0;
	};
	
	class I_AT_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 1.0;
	};
	
	class B_Parachute : Bag_Base {
		asr_camouflage = 1.1;
	};
	
	class B_UAV_01_backpack_F : Weapon_Bag_Base {
		asr_camouflage = 1.1;
	};
	
	class B_Static_Designator_01_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.8;
	};
	
	class O_Static_Designator_02_weapon_F : Weapon_Bag_Base {
		asr_camouflage = 0.8;
	};
	
	class B_OutdoorPack_Base : Bag_Base {
		asr_camouflage = 1.0;
	};
	
	class B_OutdoorPack_blk : B_OutdoorPack_Base {
		asr_camouflage = 1.1;
		asr_camouflage_night = 0.9;
	};
	class Man;	// External class reference
	
	class CAManBase : Man {
		camouflage = 2.0;
	};
	
	class Civilian : CAManBase {
		camouflage = 2.0;
	};
	class SoldierWB;	// External class reference
	
	class B_Soldier_base_F : SoldierWB {
		camouflage = 2.0;
	};
	class B_Soldier_03_f;	// External class reference
	
	class B_Soldier_lite_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	
	class B_Soldier_SL_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	
	class B_Soldier_TL_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	class B_Soldier_02_f;	// External class reference
	
	class B_medic_F : B_Soldier_02_f {
		camouflage = 2.0;
	};
	
	class B_soldier_repair_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class B_soldier_exp_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	class B_Soldier_04_f;	// External class reference
	
	class B_Helipilot_F : B_Soldier_04_f {
		camouflage = 2.0;
	};
	
	class B_Soldier_A_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class B_soldier_AT_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class B_soldier_AA_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class B_engineer_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	
	class B_crew_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	
	class B_officer_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	class B_Soldier_diver_base_F;	// External class reference
	
	class B_diver_F : B_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class B_diver_TL_F : B_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class B_diver_exp_F : B_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class B_Soldier_recon_base : B_Soldier_base_F {
		camouflage = 2.0;
	};
	class B_Soldier_sniper_base_F;	// External class reference
	
	class B_spotter_F : B_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class B_sniper_F : B_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class B_CTRG_soldier_M_medic_F : B_Soldier_03_f {
		camouflage = 2.0;
	};
	
	class B_Soldier_support_base_F : B_Soldier_base_F {
		camouflage = 2.0;
	};
	class SoldierGB;	// External class reference
	
	class I_G_Soldier_base_F : SoldierGB {
		camouflage = 2.0;
	};
	
	class I_G_Soldier_lite_F : I_G_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_G_Soldier_SL_F : I_G_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_G_Soldier_exp_F : I_G_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_G_officer_F : I_G_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_base_F : SoldierGB {
		camouflage = 2.0;
	};
	class I_Soldier_02_F;	// External class reference
	
	class I_Soldier_lite_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_A_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_SL_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_TL_F : I_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_medic_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_repair_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_exp_F : I_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class I_engineer_F : I_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_crew_F : I_Soldier_base_F {
		camouflage = 2.0;
	};
	class I_Soldier_03_F;	// External class reference
	
	class I_helipilot_F : I_Soldier_03_F {
		camouflage = 2.0;
	};
	class I_Soldier_04_F;	// External class reference
	
	class I_pilot_F : I_Soldier_04_F {
		camouflage = 2.0;
	};
	
	class I_officer_F : I_Soldier_base_F {
		camouflage = 2.0;
	};
	class I_Soldier_diver_base_F;	// External class reference
	
	class I_diver_F : I_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class I_diver_exp_F : I_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class I_diver_TL_F : I_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	class I_Soldier_sniper_base_F;	// External class reference
	
	class I_Spotter_F : I_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class I_Sniper_F : I_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class I_Soldier_support_base_F : I_Soldier_base_F {
		camouflage = 2.0;
	};
	class SoldierEB;	// External class reference
	
	class O_Soldier_base_F : SoldierEB {
		camouflage = 2.0;
	};
	
	class O_officer_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_lite_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_SL_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_TL_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_medic_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_soldier_repair_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_soldier_exp_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	class O_Soldier_02_F;	// External class reference
	
	class O_helipilot_F : O_Soldier_02_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_A_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_AT_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_AA_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_engineer_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_crew_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	class O_Soldier_diver_base_F;	// External class reference
	
	class O_diver_F : O_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class O_diver_TL_F : O_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	
	class O_diver_exp_F : O_Soldier_diver_base_F {
		camouflage = 2.0;
	};
	class O_Soldier_sniper_base_F;	// External class reference
	
	class O_spotter_F : O_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class O_sniper_F : O_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_recon_base : O_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_Soldier_support_base_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	class O_Soldier_Urban_base;	// External class reference
	
	class O_soldierU_AT_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_AAT_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_AA_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_AAA_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_TL_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_SoldierU_SL_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_repair_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_exp_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_engineer_U_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class O_soldierU_A_F : O_Soldier_Urban_base {
		camouflage = 2.0;
	};
	
	class B_ghillie_base_F : B_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class O_ghillie_base_F : O_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class I_ghillie_base_F : I_Soldier_sniper_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_base_F : I_G_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_1_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_2_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_3_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_4_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_5_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_6_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_7_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Bandit_8_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Soldier_Camo_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Pilot_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class I_C_Helipilot_F : I_C_Soldier_base_F {
		camouflage = 2.0;
	};
	
	class O_V_Soldier_base_F : O_Soldier_base_F {
		camouflage = 2.0;
	};
	class B_Soldier_F;	// External class reference
	
	class B_GEN_Soldier_base_F : B_Soldier_F {
		camouflage = 2.0;
	};
};
