// Generated by unRap v1.06 by Kegetys

class CfgWeapons {
	class Uniform_Base;	// External class reference
	
	class U_B_CombatUniform_mcam : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_CombatUniform_mcam_tshirt : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_B_CombatUniform_mcam_vest : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_GhillieSuit : Uniform_Base {
		asr_camouflage = 0.25;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_HeliPilotCoveralls : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_B_Wetsuit : Uniform_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.3;
	};
	
	class U_O_CombatUniform_ocamo : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_GhillieSuit : Uniform_Base {
		asr_camouflage = 0.25;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_PilotCoveralls : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_Wetsuit : Uniform_Base {
		asr_camouflage = 0.5;
		asr_camouflage_night = 0.4;
	};
	
	class U_B_CombatUniform_mcam_worn : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_CombatUniform_oucamo : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_SpecopsUniform_ocamo : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_OfficerUniform_ocamo : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_I_CombatUniform : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_I_CombatUniform_shortsleeve : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_I_pilotCoveralls : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_I_HeliPilotCoveralls : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_I_GhillieSuit : Uniform_Base {
		asr_camouflage = 0.25;
		asr_camouflage_ghillie = 1;
	};
	
	class U_I_OfficerUniform : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_I_Wetsuit : Uniform_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.3;
	};
	
	class U_MillerBody : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_KerryBody : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_IG_Guerilla1_1 : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_IG_Guerilla2_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_IG_Guerilla2_3 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_IG_Guerilla3_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_IG_Guerilla3_2 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_IG_leader : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_BG_Guerilla1_1 : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_BG_Guerilla2_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_BG_Guerilla2_3 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_BG_Guerilla3_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_BG_Guerilla3_2 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_BG_leader : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_OG_Guerilla1_1 : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_OG_Guerilla2_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_OG_Guerilla2_3 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_OG_Guerilla3_1 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_OG_Guerilla3_2 : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_OG_leader : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_C_WorkerOveralls : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_C_WorkerCoveralls : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_C_HunterBody_grn : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_C_HunterBody_brn : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_B_CTRG_1 : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_CTRG_2 : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_B_CTRG_3 : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_survival_uniform : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_I_G_Story_Protagonist_F : Uniform_Base {
		asr_camouflage = 0.5;
		asr_camouflage_night = 0.4;
	};
	
	class U_I_G_resistanceLeader_F : Uniform_Base {
		asr_camouflage = 0.55;
		asr_camouflage_night = 0.4;
	};
	
	class U_C_Journalist : Uniform_Base {
		asr_camouflage = 0.55;
		asr_camouflage_night = 0.4;
	};
	
	class U_IG_Guerrilla_6_1 : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_BG_Guerrilla_6_1 : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_OG_Guerrilla_6_1 : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_B_FullGhillie_lsh : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_FullGhillie_sard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_FullGhillie_ard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_FullGhillie_lsh : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_FullGhillie_sard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_FullGhillie_ard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_I_FullGhillie_lsh : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_I_FullGhillie_sard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_I_FullGhillie_ard : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_T_Soldier_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_T_Soldier_AR_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_B_T_Soldier_SL_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_T_Sniper_F : Uniform_Base {
		asr_camouflage = 0.25;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_T_FullGhillie_tna_F : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_B_CTRG_Soldier_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_CTRG_Soldier_2_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_B_CTRG_Soldier_3_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_GEN_Soldier_F : Uniform_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.3;
	};
	
	class U_B_GEN_Commander_F : Uniform_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.3;
	};
	
	class U_O_T_Soldier_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_T_Officer_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_T_Sniper_F : Uniform_Base {
		asr_camouflage = 0.25;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_T_FullGhillie_tna_F : Uniform_Base {
		asr_camouflage = 0.2;
		asr_camouflage_ghillie = 1;
	};
	
	class U_O_V_Soldier_Viper_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_O_V_Soldier_Viper_hex_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_I_C_Soldier_Para_1_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_I_C_Soldier_Para_2_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_I_C_Soldier_Para_3_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_I_C_Soldier_Para_4_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_I_C_Soldier_Para_5_F : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_I_C_Soldier_Bandit_1_F : Uniform_Base {
		asr_camouflage = 0.4;
	};
	
	class U_I_C_Soldier_Bandit_3_F : Uniform_Base {
		asr_camouflage = 0.7;
	};
	
	class U_I_C_Soldier_Camo_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_CTRG_Soldier_urb_1_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	
	class U_B_CTRG_Soldier_urb_2_F : Uniform_Base {
		asr_camouflage = 0.35;
	};
	
	class U_B_CTRG_Soldier_urb_3_F : Uniform_Base {
		asr_camouflage = 0.3;
	};
	class Vest_Camo_Base;	// External class reference
	class Vest_NoCamo_Base;	// External class reference
	
	class V_PlateCarrier1_rgr : Vest_NoCamo_Base {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrier2_rgr : V_PlateCarrier1_rgr {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrier2_blk : V_PlateCarrier2_rgr {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_PlateCarrier3_rgr : Vest_NoCamo_Base {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrierGL_rgr : Vest_NoCamo_Base {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrierGL_blk : V_PlateCarrierGL_rgr {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_PlateCarrierGL_mtp : V_PlateCarrierGL_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrier1_blk : Vest_Camo_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_PlateCarrierSpec_rgr : Vest_NoCamo_Base {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrierSpec_blk : V_PlateCarrierSpec_rgr {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_PlateCarrierSpec_mtp : V_PlateCarrierSpec_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_TacVest_khk : Vest_Camo_Base {
		asr_camouflage = 0.4;
	};
	
	class V_TacVest_brn : V_TacVest_khk {
		asr_camouflage = 0.4;
	};
	
	class V_TacVest_oli : V_TacVest_khk {
		asr_camouflage = 0.4;
	};
	
	class V_TacVest_blk : V_TacVest_khk {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_TacVest_camo : Vest_Camo_Base {
		asr_camouflage = 0.3;
	};
	
	class V_TacVest_blk_POLICE : Vest_Camo_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_TacVestIR_blk : Vest_NoCamo_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_TacVestCamo_khk : Vest_Camo_Base {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierIA1_dgtl : Vest_NoCamo_Base {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierIA2_dgtl : V_PlateCarrierIA1_dgtl {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierIAGL_dgtl : V_PlateCarrierIA2_dgtl {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierIAGL_oli : V_PlateCarrierIAGL_dgtl {
		asr_camouflage = 0.4;
	};
	
	class V_RebreatherB : Vest_Camo_Base {
		asr_camouflage = 0.7;
		asr_camouflage_night = 0.5;
	};
	
	class V_RebreatherIR : V_RebreatherB {
		asr_camouflage = 0.4;
	};
	
	class V_RebreatherIA : V_RebreatherB {
		asr_camouflage = 0.4;
	};
	
	class V_PlateCarrierL_CTRG : V_PlateCarrier1_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierH_CTRG : V_PlateCarrier2_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_I_G_resistanceLeader_F : V_TacVest_camo {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrier1_tna_F : V_PlateCarrier1_blk {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrier2_tna_F : V_PlateCarrier2_blk {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierSpec_tna_F : V_PlateCarrierSpec_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_PlateCarrierGL_tna_F : V_PlateCarrierGL_rgr {
		asr_camouflage = 0.3;
	};
	
	class V_HarnessO_brn : Vest_NoCamo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_HarnessOGL_brn : Vest_NoCamo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_Rangemaster_belt : Vest_NoCamo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_BandollierB_khk : Vest_Camo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_Chestrig_khk : Vest_Camo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_Chestrig_oli : Vest_Camo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_TacChestrig_grn_F : Vest_Camo_Base {
		asr_camouflage_ignore = 1;
	};
	
	class V_DeckCrew_base_F : Vest_Camo_Base {
		asr_camouflage = 1;
	};
};
