// config.bin - 11:33:59 08/29/17, generated in 0.12 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgAddons.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
